kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    registry: docker.io
    repo: mytinywms/mytinywms
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
  when:
    branch:
    - master
