kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    registry: docker.io
    repo:
      from_secret: docker_repo
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
