kind: pipeline
name: default

steps:
#- name: build  
#  image: plugins/docker
#  settings:
#    registry: docker.io
#    repo: mytinywms/mytinywms
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#    tags: latest
    
- name: test
  image: docker/compose
  commands:
    - docker-compose -f docker-compose.yml.test up -d
    
image_pull_secrets:
- dockerconfig
