version: '2'
services:
  app:
    container_name: wms_app
    hostname: app
    image: mytinywms/mytinywms
    #build:
    #  context: .
    links:
    - db
    - redis
    environment:
    - APP_NAME="myTinyWMS"
    - APP_ENV=local
    - APP_DEBUG=true
    - DEMO_MODE=false
    - APP_KEY=base64:sgppryzAzGfrijoL5hW5a6CxXO/95IlYasKP7wDT3RE=
    - APP_URL=http://localhost/
    - LOGO_PATH=
    - HORIZON_NOTIFICATION_RECEIVER=
    - INVENTORY_MANUAL_RECEIVER=
    - INVENTORY_AUTOMATIC_RECEIVER=
    - MYSQL_PORT_3306_TCP_ADDR=db
    - MYSQL_PORT_3306_TCP_PORT=3306
    - MYSQL_DATABASE=mss_test
    - MYSQL_USER=root
    - MYSQL_PASSWORD=mss
    - APP_QUEUE_DRIVER=sync
    - APP_CACHE_DRIVER=redis
    - APP_SESSION_DRIVER=redis
    - REDIS_PORT_6379_HOST=redis
    - REDIS_PORT_6379_PASSWORD=null
    - REDIS_PORT_6379_PORT=6379
    - MAIL_PORT_587_TCP_ADDR=
    - MAIL_PORT_587_TCP_PORT=
    - MAIL_ENV_USERNAME=
    - MAIL_ENV_PASSWORD=
    - MAIL_ENV_ENCRYPTION=
    - MAIL_ENV_FROM_ADDR=
    - MAIL_ENV_FROM_NAME=
    - MAIL_IMAP_HOST=
    - MAIL_IMAP_PORT=
    - MAIL_IMAP_ENCRYPTION=
    - MAIL_IMAP_USERNAME=
    - MAIL_IMAP_PASSWORD=
    - AUTH_DRIVER=eloquent
    volumes:
    - ./data/storage:/data/www/storage
    - ./data/cache:/data/www/bootstrap/cache

  db:
    container_name: wms_db
    image: mariadb:10.2
    environment:
    - MYSQL_DATABASE=mss_test
    - MYSQL_ROOT_PASSWORD=mss
    - MYSQL_USER=mss
    - MYSQL_PASSWORD=mss
    volumes:
    - ./data/db:/var/lib/mysql

  redis:
    container_name: wms_redis
    image: redis

  selenium:
    container_name: mss_selenium
    image: robcherry/docker-chromedriver
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_PORT: "4444"
    depends_on:
      - app
    links:
      - app:mss.test
    volumes:
      - /dev/shm:/dev/shm
    cap_add:
      - "SYS_ADMIN"
