version: '2'
services:
  app:
    container_name: mss_app
    hostname: app
    build:
      context: .
    image: project_mss
    links:
    - db
#    - db_onp
    - redis
    ports:
    - 3080:80
    - 30443:443
    volumes:
    - .:/data/www
    - ./data/storage:/data/www/storage
    - ./data/cache:/data/www/bootstrap/cache
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/default-site:/etc/nginx/sites-enabled/default
    - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    environment:
    - DEBUG=1
    - DB_PASSWORD=mss
    # for debugging
    - TERM=xterm
    tmpfs:
    - /ramdisk:rw,noexec,nosuid,size=50M
    command: supervisord -c /etc/supervisor/supervisord.conf

  db:
    container_name: mss_db
    build:
      context: .
      dockerfile: Dockerfile-DB
    image: project_mss_db
    environment:
    - MYSQL_ROOT_PASSWORD=mss
    - MYSQL_DATABASE=mss
    volumes:
    - ./data/db:/var/lib/mysql
    ports:
    - "24306:3306"

  redis:
    container_name: mss_redis
    image: redis

#  db_onp:
#    container_name: mss_onp_db
#    image: postgres:9.6
#    environment:
#      POSTGRES_PASSWORD: mss
#      POSTGRES_DB: fcp
#    ports:
#    - "24432:5432"