version: '3'
services:
  app:
    container_name: mss_app
    build:
      context: .
    image: project_mss
    links:
    - db
    - redis
    ports:
    - 3080:80
    - 30443:443
    volumes:
    - .:/data/www
    - ./data/storage:/data/www/storage
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    environment:
    - DEBUG=1
    - DB_PASSWORD=mss
    # for debugging
    - TERM=xterm
    tmpfs:
    - /ramdisk:rw,noexec,nosuid,size=50M
    - /data/www/bootstrap/cache:rw,noexec,nosuid,size=50M
    command: supervisord -c /etc/supervisor/supervisord.conf

  db:
    container_name: mss_db
    image: mariadb:10.1
    environment:
    - MYSQL_ROOT_PASSWORD=mss
    - MYSQL_DATABASE=mss
    volumes:
    - ./data/db:/var/lib/mysql
    ports:
    - "24306:3306"

  redis:
    container_name: mss_redis
    image: redis