version: '2'
services:
  app:
    container_name: wms_app
    hostname: app
    image: mytinywms/mytinywms
    links:
    - db
    - redis
    ports:
    - 80:80
    volumes:
    - ./.env:/data/www/.env
    - ./data/storage:/data/www/storage
    - ./data/cache:/data/www/bootstrap/cache

  db:
    container_name: wms_db
    image: mariadb:10.2
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./data/db:/var/lib/mysql

  redis:
    container_name: wms_redis
    image: redis