version: '2'
services:
  app:
    container_name: mss_app
    hostname: app
    build:
      context: .
    image: mytinywms/mytinywms
    links:
    - db
    - redis
    - mailhog
    ports:
    - 3080:80
    - 30443:443
    env_file:
    - ./.env
    volumes:
    - .:/data/www
    - ./data/storage:/data/www/storage
    - ./data/cache:/data/www/bootstrap/cache
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/ssl:/etc/nginx/ssl
    - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf

  db:
    container_name: mss_db
    build:
      context: .
      dockerfile: Dockerfile-DB
    image: project_mss_db
    environment:
    - MYSQL_DATABASE=${DB_DATABASE}
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MYSQL_USER=${DB_USERNAME}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./data/db:/var/lib/mysql
    ports:
    - "24306:3306"

  redis:
    container_name: mss_redis
    image: redis

  mailhog:
    container_name: mss_mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  selenium:
    container_name: mss_selenium
    image: robcherry/docker-chromedriver
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_PORT: "4444"
    ports:
      - 4444:4444
    depends_on:
      - app
    links:
      - app:mss.test
    volumes:
      - /dev/shm:/dev/shm
    cap_add:
      - "SYS_ADMIN"